name: EDT Data Build Tool Platform CICD

on:
  push:
    branches:
      - main

env:
  AWS_REGION: <your_aws_region>
  ECR_REPOSITORY: <your_ecr_repository_name>

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push custom data build tool Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest
